[package]
name = "salmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
nom = "7.1.0"
nom_locate = "4.0.0"
